name: ValidateExamples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Validations/Validations.csproj
    - name: Test
      run: dotnet test --logger trx --results-directory "TestResults" Validations/Validations.csproj
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-results
        path: TestResults
      if: ${{ always() }}

